port = 10000

[[models]]
name = "Qwen/Qwen2.5-Coder-7B-Instruct"
base_url = "https://api.siliconflow.cn/v1"
token_name = "SILICONFLOW_API_TOKEN"

[[models]]
name = "Qwen/Qwen2.5-7B-Instruct"
base_url = "https://api.siliconflow.cn/v1"
token_name = "SILICONFLOW_API_TOKEN"

[[models]]
name = "Qwen/Qwen2.5-7B-Instruct"
base_url = "https://api.siliconflow.cn/v1"
token_name = "SILICONFLOW_API_TOKEN"

[[models]]
name = "deepseek-chat"
base_url = "https://api.deepseek.com/v1"
token_name = "DEEPSEEK_API_TOKEN"

[[models]]
name = "deepseek-coder"
base_url = "https://api.deepseek.com/v1"
token_name = "DEEPSEEK_API_TOKEN"
